PIPELINE_CV:
  cv_source: "../input/cv.md"
  website_public_repo: "/Users/johnmclevey/Vaults/EC2/websites/mclevey.github.io"
  website_source_repo: "/Users/johnmclevey/Vaults/EC2/websites/mclevey.github.io-source"
  cv_qmd_website_source_path: "/Users/johnmclevey/Vaults/EC2/websites/mclevey.github.io-source/pages/cv.qmd"


